services:
  web:
    build:
      context: django_my_website
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
  mysql:
    build:
      context: databases
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=qmqmqm8c3
  web_server:
    build:
      context: web_server
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  
