# Generated by Django 5.0.2 on 2024-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('total_view', models.SmallIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'bar',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('total_view', models.SmallIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
