---
- hosts: website-server
  become: yes
  name: Install necessary package
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name:
          - git
    - name: Install python mysql module to use ansible mysql
      ansible.builtin.apt:
        name:
          - python3-mysqldb
    - name: Install lsof
      ansible.builtin.apt:
        name:
          - lsof
    - name: Install python venv setup
      ansible.builtin.apt:
        name:
          - python3-venv
    - name: Install python pip module
      ansible.builtin.apt:
        name:
          - python3-pip
    - name: Install virtual env through pip
      ansible.builtin.pip:
        name:
          - virtualenv
    - name: Install supervisor for manage processeses
      ansible.builtin.apt:
        name:
          - supervisor
    - name: Add openresty GPG key
      ansible.builtin.apt_key:
        url: https://openresty.org/package/pubkey.gpg
    - name: Add openresty repository
      ansible.builtin.apt_repository:
        repo: deb http://openresty.org/package/debian bullseye openresty
    - name: Install openresty
      ansible.builtin.apt:
        name:
          - openresty