---
- hosts: website_server
  become: yes
  name: Install necessary package
  tasks:
    - name: Install git for first time deployment
      ansible.builtin.apt:
        name:
          - git
    - name: Install lsof for checking port 
      ansible.builtin.apt:
        name:
          - lsof
    - name: Install python venv setup
      ansible.builtin.apt:
        name:
          - python3-venv
    - name: Install python pip module
      ansible.builtin.apt:
        name:
          - python3-pip
    - name: Install virtual env through pip
      ansible.builtin.pip:
        name:
          - virtualenv
    - name: Install supervisor for manage processeses
      ansible.builtin.apt:
        name:
          - supervisor
    - name: Add openresty GPG key
      ansible.builtin.apt_key:
        url: https://openresty.org/package/pubkey.gpg
    - name: Add openresty repository
      ansible.builtin.apt_repository:
        repo: deb http://openresty.org/package/debian bullseye openresty
    - name: Install openresty
      ansible.builtin.apt:
        name:
          - openresty
    - name: Add Docker host to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 host.docker.internal