---
- hosts: website-server
  name: Reload server
  become: yes
  tasks:
    - name: Reload openresty server
      ansible.builtin.command:
        chdir: /opt/my_website/web_server
        cmd: openresty -c nginx.conf -p /opt/my_website/web_server -s reload