---
- hosts: website_server
  become: yes
  gather_facts: no
  tasks: 
    - name: Create the virtual environment 
      ansible.builtin.pip:
        requirements: /opt/my_website/django_my_website/requirements.txt
        virtualenv: /opt/my_website_venv
        virtualenv_python: python3
    - name: Run gunicorn HTTP server
      community.general.gunicorn:
        app: "django_my_website.wsgi"
        chdir: /opt/my_website/django_my_website
        venv: /opt/my_website_venv
