---
- hosts: website-server
  name: Running server
  become: yes
  tasks:
    - name: Stop Openresty service
      ansible.builtin.service:
        name: openresty
        state: stopped
    - name: Running openresty server
      ansible.builtin.command:
        chdir: /opt/my_website/web_server
        cmd: openresty -c nginx.conf -p /opt/my_website/web_server