---
- hosts: website-server
  become: True
  tasks: 
    - name: Copy log analyze supervisor config file from git repo to supervisor folder.
      ansible.builtin.copy:
        src: /opt/my_website/log_analyzer/log_analyze.conf
        dest: /etc/supervisor/conf.d/log_analyze.conf
        remote_src: true
    
    - name: Reread supervisor config
      ansible.builtin.command:
        cmd: supervisorctl reread

    - name: Run python cache delete using supervisor
      ansible.builtin.command:
        cmd: supervisorctl start all
    
    - name: Reload supervisorctl
      ansible.builtin.command:
        cmd: supervisorctl reload