---
- hosts: website_server
  become: True
  tasks: 
    - name: Copy log analyze supervisor config file from git repo to supervisor folder.
      ansible.builtin.copy:
        src: /opt/my_website/log_analyzer/log_analyzer.conf
        dest: /etc/supervisor/conf.d/log_analyzer.conf
        remote_src: true
    
    - name: Reread supervisor config
      ansible.builtin.command:
        cmd: supervisorctl reread

    - name: Run python cache delete using supervisor
      ansible.builtin.command:
        cmd: supervisorctl start all
    
    - name: Reload supervisorctl
      ansible.builtin.command:
        cmd: supervisorctl reload

    - name: Copy file prometheus config
      ansible.builtin.copy:
        src: /opt/my_website/log_analyzer/prometheus.yml
        dest: /etc/prometheus/
        remote_src: true
    - name: Reload prometheus
      ansible.builtin.systemd:
        name: prometheus.service
        state: reloaded
