--- 
- hosts: website_server
  become: yes
  name: Synchronize code using github
  tasks:
    - name: Pulling code from github
      ansible.builtin.git:
        repo: https://github.com/NguyenQuangMinh0504/my_website
        dest: /opt/my_website
        update: yes
        clone: yes
        force: yes